name: CI
on:
  pull_request:
    branches:
      - dev
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Git pull
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git merge origin/${{ github.head_ref }} --allow-unrelated-histories
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Change yarn version
        run: yarn policies set-version 1.22.15
      - name: Install packages
        working-directory: Api/Client
        run: yarn
      - name: Build
        working-directory: Api/Client
        run: yarn build
  build_backend:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Git pull
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git merge origin/${{ github.head_ref }} --allow-unrelated-histories
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
      - name: Build
        run: dotnet build -c Release
  analyze:
    runs-on: windows-latest
    environment: development
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: 11
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Git pull
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git merge origin/${{ github.head_ref }} --allow-unrelated-histories
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          dotnet new tool-manifest
          dotnet tool install --local dotnet-sonarscanner
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: powershell
        run: |
          dotnet sonarscanner begin /k:"F-Hostel-Management" /o:"f-hostel-management" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.branch.name="dev"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
  report:
    runs-on: ubuntu-latest
    needs: [analyze]
    steps:
      - name: SonarCloud analysis report
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            [![Code Smells](https://sonarcloud.io/api/project_badges/measure?project=F-Hostel-Management&metric=code_smells)](https://sonarcloud.io/summary/new_code?id=F-Hostel-Management)
            [![Technical Debt](https://sonarcloud.io/api/project_badges/measure?project=F-Hostel-Management&metric=sqale_index)](https://sonarcloud.io/summary/new_code?id=F-Hostel-Management)
            [![Reliability Rating](https://sonarcloud.io/api/project_badges/measure?project=F-Hostel-Management&metric=reliability_rating)](https://sonarcloud.io/summary/new_code?id=F-Hostel-Management)
            [![Duplicated Lines (%)](https://sonarcloud.io/api/project_badges/measure?project=F-Hostel-Management&metric=duplicated_lines_density)](https://sonarcloud.io/summary/new_code?id=F-Hostel-Management)
            [![Vulnerabilities](https://sonarcloud.io/api/project_badges/measure?project=F-Hostel-Management&metric=vulnerabilities)](https://sonarcloud.io/summary/new_code?id=F-Hostel-Management)
            [![Bugs](https://sonarcloud.io/api/project_badges/measure?project=F-Hostel-Management&metric=bugs)](https://sonarcloud.io/summary/new_code?id=F-Hostel-Management)
            [![Security Rating](https://sonarcloud.io/api/project_badges/measure?project=F-Hostel-Management&metric=security_rating)](https://sonarcloud.io/summary/new_code?id=F-Hostel-Management)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
