name: CI
on:
  pull_request:
    branches:
      - dev
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Git pull
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git merge origin/${{ github.head_ref }} --allow-unrelated-histories
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        working-directory: Api/Client
        run: yarn
      - name: Build
        working-directory: Api/Client
        run: yarn build
  build_backend:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      - name: Git pull
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git merge origin/${{ github.head_ref }} --allow-unrelated-histories
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
      - name: Build
        run: dotnet build -c Release
